### ISSUE TITLE
@Retry on CompletionStage do not work as expected

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-fault-tolerance#350]
Let's imagine that bean:

```java
@ApplicationScoped
public static class FailingProcessorOfPayloadCS {
    volatile int attempt = 0;


    @Retry // 3 is the default
    public CompletableFuture<Integer> process(int i) {

        return CompletableFuture.supplyAsync(() -> {
            System.out.println("called with " + i);
            if (attempt < 3 && i == 3) {
                attempt = attempt + 1;
                throw new ArithmeticException("boom");
            }
            return i + 1;
        });
    }
}
```

and the following test:

```java
@Test
public void testRetryOnPayloadProcessorCS2() {
    addBeanClass(FailingProcessorOfPayloadCS.class);
    initialize(); // Start weld
    FailingProcessorOfPayloadCS processor = get(FailingProcessorOfPayloadCS.class); // Get the bean
    assertThat(processor.process(1).toCompletableFuture().join()).isEqualTo(2);
    assertThat(processor.process(2).toCompletableFuture().join()).isEqualTo(3);
    assertThat(processor.process(3).toCompletableFuture().join()).isEqualTo(4);
    assertThat(processor.process(4).toCompletableFuture().join()).isEqualTo(5);
}
```

Because of the `@Retry`, this should work. However, it reports:

```
java.util.concurrent.CompletionException: java.lang.ArithmeticException: boom

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:325)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1772)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1762)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1018)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1667)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1600)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
Caused by: java.lang.ArithmeticException: boom
	at io.smallrye.reactive.messaging.ft.RetryTest$FailingProcessorOfPayloadCS.lambda$process$0(RetryTest.java:316)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	... 6 more
```

The retry didn't happen, and `processor.process(3)` is called only once.

**Comment by cescoffier** [comment]
NOTE: If the issue is synchronous, it works smoothly. The problem seems to be the asynchronous error.

**Comment by Ladicek** [comment]
This won't be retried, because the method returns a value successfully. It seems you want "asynchronous retry", but for that, you need: 1. the return type to be a `CompletionStage`, not a subtype; 2. the method to have at least one of these annotations: `@Asynchronous`, `@Blocking`, `@NonBlocking`.

**Comment by Ladicek** [comment]
Ah and my comment applies to 5.0 (where you can have more async types, such as `Uni`, but still not `CompletableFuture`). In 4.x, only `@Asynchronous` is recognized.

**Comment by cescoffier** [comment]
Damn! As soon as I added `@Asynchronous` everything started to work! Thanks!

(closing)
