### ISSUE TITLE
Distribute a multi-release jar

### ISSUE THREAD

**Issue by bstansberry** [smallrye/smallrye-fault-tolerance#420]
The code includes multi-release source (https://github.com/smallrye/smallrye-fault-tolerance/tree/main/implementation/fault-tolerance/src/main/java9) but the 5.0.0 zip on maven central does not include it.

The result is when I try and test smallrye FT on WildFly with SE 16 or later I get:

```
java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @35f1d892
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at io.smallrye.fault-tolerance//io.smallrye.faulttolerance.DefaultMethodFallbackProvider.getFallback(DefaultMethodFallbackProvider.java:19)
```

WF is going to have to add some --add-opens to run on SE 16+ but it would be good to not need this one.

**Comment by Ladicek** [comment]
This is fixed in #409, which will be part of 5.1.0.

**Comment by bstansberry** [comment]
Thanks, Ladicek!

**Comment by Ladicek** [comment]
FYI 5.1.0 was released yesterday (also CC @rhusar).

**Comment by rhusar** [comment]
@Ladicek Thanks, PR is up.
