### ISSUE TITLE
Fallback handler in rest client failing at runtime

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-fault-tolerance#440]
With the following rest client, at runtime (on failure), I get an unsatisfied resolution issue:

```
@RegisterRestClient(configKey = "greeting-service")
public interface GreetingService {

    @GET
    @Path("/")
    @NonBlocking
    @Fallback(GreetingFallback.class)
    Uni<String> greeting(@QueryParam("name") String name);

    class GreetingFallback implements FallbackHandler<Uni<String>> {
        @Override
        public Uni<String> handle(ExecutionContext context) {
            return Uni.createFrom().item("Hello fallback");
        }
    }
}
```

The stack trace is:

```
 javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class org.eclipse.microprofile.faulttolerance.Fallback$DEFAULT] and qualifiers [[@javax.enterprise.inject.Any()]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:175)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	at io.quarkus.smallrye.faulttolerance.runtime.QuarkusFallbackHandlerProvider$1.handle(QuarkusFallbackHandlerProvider.java:34)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$prepareFallbackFunction$8(FaultToleranceInterceptor.java:517)
	at io.smallrye.faulttolerance.core.fallback.CompletionStageFallback.lambda$doApply$0(CompletionStageFallback.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.smallrye.faulttolerance.core.util.CompletionStages.lambda$propagateCompletion$0(CompletionStages.java:30)
	at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:58)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.jboss.resteasy.reactive.client.handlers.ClientErrorHandler.handle(ClientErrorHandler.java:13)
	at org.jboss.resteasy.reactive.client.handlers.ClientErrorHandler.handle(ClientErrorHandler.java:9)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:132)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I use Quarkus 2.0.0.CR3

**Comment by Ladicek** [comment]
This is really weird, and I can't reproduce locally. It's as if `@Fallback` didn't have the `value` attribute defined.

Do you have a reproducing project I can try?

**Comment by cescoffier** [comment]
Here: https://github.com/cescoffier/reactive-systems-in-java/tree/ft-reproducer-440/chapter-12/api-gateway-example/api-gateway

(same as for the #439 but different branch).

I reproduce it by running:

```
> mvn quarkus:dev
# In another terminal
> http :8080/quote
```

**Comment by Ladicek** [comment]
The cause here is very similar to #439: when generating the RestClient bean class, annotations are copied, but not their attributes. So the intercepted method actually has `@Fallback`, not `@Fallback(GreetingFallback.class)`. Nothing I can fix on FT front.

**Comment by cescoffier** [comment]
@michalszynkiewicz oups...

**Comment by Ladicek** [comment]
Well, to be 100% honest, it's not 100% RESTEasy Reactive's fault. Gizmo is lacking support for writing class-typed annotation attributes, and instead of throwing (which is what happens for nested annotations), it just drops the attribute altogether :-) Will continue investigating tomorrow.

**Comment by Ladicek** [comment]
OK, so I have implemented the missing pieces in Gizmo to properly copy all annotation attributes, and now Fault Tolerance complains that the `FallbackHandler` is for type `Uni<String>`, which doesn't match the guarded method, which returns `Uni` (see #439 for why). So I'll have to implement generic signature reconstruction anyway :-)

**Comment by Ladicek** [comment]
This PR https://github.com/quarkusio/quarkus/pull/17984 is a proper fix.
