### ISSUE TITLE
@Retry / @Retry.retryOn not working as expected

### ISSUE THREAD

**Issue by ManasMaji** [smallrye/smallrye-fault-tolerance#819]
I am using `quarkus` (2.15.0.Final) for my application, in which I have method with `@Retry` that calls an Azure API. The Azure API takes in a `timeout`, and if a response is not returned before the timeout concludes a `RuntimeException` will be thrown by Azure. I am catching the `RuntimeException` and throwing my own `QueueDeleteMessageException`, which I want to retry on.

```
  @ExponentialBackoff(maxDelay = 0)
  @Retry(delay = 2, delayUnit = ChronoUnit.SECONDS, maxRetries = 10, maxDuration = 0, retryOn = { QueueDeleteMessageException.class })
  private void deleteMessage(...) {
    try {
      Response<Void> response = azureQueueclient.deleteMessageWithResponse(messageId, popReceipt, timeout, Context.NONE);
      // application logic
    } catch (RuntimeException deleteMessageException) {
      // retry
      throw new QueueDeleteMessageException();
    }
  }
```
The issue is the retry is not working as expected, the `QueueDeleteMessageException` is thrown but the method is not retried. 

I set the logging level for the fault-tolerance package, but didn't see any useful logs.
`quarkus.log.category."io.smallrye.faulttolerance.core".level=DEBUG`

The stack trace looks like :
```
   java.lang.IllegalStateException: Timeout on blocking read for 5000000000 NANOSECONDS
   at com.test.move.service.AzureQueueService.deleteMessage(AzureQueueService.java:418)
   at com.test.move.service.AzureQueueService.deleteMessage(AzureQueueService.java:395)
   at com.test.move.service.AzureQueueService.processMessageQueue(AzureQueueService.java:325)
   at com.test.move.service.AzureQueueService_Subclass.processMessageQueue$$superforward1(Unknown Source)
   at com.test.move.service.AzureQueueService_Subclass$$function$$5.apply(Unknown Source)
   at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
   at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$3(FaultToleranceInterceptor.java:257)
   at io.smallrye.faulttolerance.core.InvocationContext.call(InvocationContext.java:20)
   at io.smallrye.faulttolerance.core.Invocation.apply(Invocation.java:29)
   at io.smallrye.faulttolerance.core.retry.Retry.doApply(Retry.java:88)
   at io.smallrye.faulttolerance.core.retry.Retry.apply(Retry.java:42)
   at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:259)
   at io.smallrye.faulttolerance.FaultToleranceInterceptor.intercept(FaultToleranceInterceptor.java:186)
   at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(Unknown Source)
   at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
   at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
   at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
   at com.test.move.service.AzureQueueService_Subclass.processMessageQueue(Unknown Source)
   at com.test.move.service.AzureQueueService_ClientProxy.processMessageQueue(Unknown Source)
   at com.test.move.MoveApplication.run(MoveApplication.java:125)
   at com.test.move.MoveApplication.run(Unknown Source)
   at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:130)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
   ...
```

cc. @Ladicek

**Comment by Ladicek** [comment]
This looks OK, I can't see a reason why this shouldn't work. Do you perhaps have some configuration that would override the annotation values (in your `application.properties`)?

**Comment by ManasMaji** [comment]
The only annotations we have regarding `retry` is K8s HTTP operation retry configurations (max 5 retries, with initial delay of 5s)
```
quarkus.kubernetes-client.request-retry-backoff-limit=5
quarkus.kubernetes-client.request-retry-backoff-interval=PT5S
```
We use `@Retry` in a number of places in our application to deal with transient errors, and the weirdest thing is that most of them are working as expected, but not in this case.

**Comment by Ladicek** [comment]
Ah ah! I'm looking at the code again and I see the method is `private`. That's the problem -- `private` methods are not intercepted. You need to make the method at least package-private.

If you look carefully at the stack trace, you'll see that the `processMessageQueue` is intercepted (you don't show the method, but the stack trace reveals it also has a `@Retry` annotation), but the `deleteMessage` method is _not_.

**Comment by ManasMaji** [comment]
Oh! I'll try that. Thanks for the help @Ladicek!
